version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgresql'
    environment:
      - 'POSTGRES_USER=vianny'
      - 'POSTGRES_PASSWORD=TESTPASSWORD'
      - 'POSTGRES_DB=door_db'
    volumes:
      - /home/postgresql/data:/var/lib/postgresql/data
    ports:
      - "1111:5432"
    networks:
      - door-network

  minio:
    image: minio/minio
    container_name: 'minio'
    ports:
      - "2222:9000"
    environment:
      - 'MINIO_ACCESS_KEY=vianny'
      - 'MINIO_SECRET_KEY=TESTPASSWORD'
    volumes:
      - /home/minio/data:/data
    command: server /data
    networks:
      - door-network

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - "3333:6379"
    command: '--requirepass TESTPASSWORD'
    networks:
      - door-network

  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - "44444:27017"
    volumes:
      - /home/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: vianny
      MONGO_INITDB_ROOT_PASSWORD: TESTPASSWORD
    networks:
      - door-network

  java-app:
    build: ./
    container_name: 'dverivariant'
    volumes:
      - ./logs:/logs
    ports:
      - "5555:8080"
    networks:
      - door-network

networks:
  door-network:
    driver: bridge