version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=door_db'
    volumes:
      - /mnt/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: 'minio'
    ports:
      - "9000:9000"
    environment:
      - 'MINIO_ACCESS_KEY=minio'
      - 'MINIO_SECRET_KEY=miniokey'
    volumes:
      - /mnt/minio/data:/data
    command: server /data

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - "6379:6379"
    command: '--requirepass rediskey'

  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - "27017:27017"
    volumes:
      - /mnt/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongokey

  java-app:
    build: ./
    container_name: 'dverivariant'
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
